# Generated by Django 5.2.5 on 2025-08-09 00:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('terrain', 'terrain'), ('office', 'office'), ('store', 'store'), ('warehouse', 'warehouse'), ('rural', 'rural')], max_length=15), null=True, size=None)),
                ('transaction_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], max_length=15), null=True, size=None)),
                ('city', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('neighborhood', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('bedroom_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('suite_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bathroom_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('garage_slots_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('min_area', models.FloatField()),
                ('max_area', models.FloatField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_status', models.CharField(choices=[('not_started', 'not started'), ('started', 'started'), ('partial', 'partial'), ('finished', 'finished')], default='not_started', max_length=15)),
                ('number_real_estate_found', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.filter')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultRealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
    ]
