# Generated by Django 5.2 on 2025-05-01 18:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('S1', 'apartment'), ('S2', 'house'), ('S3', 'terrain'), ('S4', 'office'), ('S5', 'store'), ('S6', 'warehouse'), ('S7', 'rural')], max_length=2), null=True, size=None)),
                ('transaction_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('S1', 'buy'), ('S2', 'rent')], max_length=2), null=True, size=None)),
                ('city', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(max_length=1000)),
                ('bedroom_quantity', models.IntegerField()),
                ('suite_quantity', models.IntegerField()),
                ('bathroom_quantity', models.IntegerField()),
                ('garage_slots_quantity', models.IntegerField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('min_area', models.FloatField()),
                ('max_area', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_status', models.CharField(choices=[('S1', 'not_started'), ('S2', 'started'), ('S3', 'partial'), ('S4', 'finished')], default='S1', max_length=2)),
                ('number_real_estate_found', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.filter')),
            ],
        ),
    ]
