# Generated by Django 5.2 on 2025-05-11 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_realestate_url'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultRealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
    ]
