# Generated by Django 5.2 on 2025-05-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='query_status',
            field=models.CharField(choices=[('S1', 'not started'), ('S2', 'started'), ('S3', 'partial'), ('S4', 'finished')], default='S1', max_length=2),
        ),
    ]
