# Generated by Django 5.2 on 2025-05-03 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_filter_created_by_alter_search_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='property_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('terrain', 'terrain'), ('office', 'office'), ('store', 'store'), ('warehouse', 'warehouse'), ('rural', 'rural')], max_length=15), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='filter',
            name='transaction_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], max_length=15), null=True, size=None),
        ),
    ]
