# Generated by Django 5.2 on 2025-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_filter_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='query_status',
            field=models.CharField(choices=[('not_started', 'not started'), ('started', 'started'), ('partial', 'partial'), ('finished', 'finished')], default='not_started', max_length=15),
        ),
    ]
