# Generated by Django 5.2.4 on 2025-07-31 22:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radarrealestatereview',
            name='bad_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('paint', 'paint'), ('space', 'space'), ('condo fee', 'condo fee'), ('price', 'price'), ('finishing', 'finishing'), ('floors', 'floors'), ('ceiling', 'ceiling'), ('moldings', 'moldings'), ('natural light', 'natural light'), ('ventilation', 'ventilation'), ('windows', 'windows'), ('doors', 'doors'), ('closets', 'closets'), ('built-in cabinets', 'built-in cabinets'), ('kitchen counter', 'kitchen counter'), ('bathroom counters', 'bathroom counters'), ('air conditioning', 'air conditioning'), ('heating', 'heating'), ('fireplace', 'fireplace'), ('view', 'view'), ('balcony', 'balcony'), ('garden', 'garden'), ('landscaping', 'landscaping'), ('garage spaces', 'garage spaces'), ('guest parking', 'guest parking'), ('social elevator', 'social elevator'), ('service elevator', 'service elevator'), ('pool', 'pool'), ('party room', 'party room'), ('game room', 'game room'), ('kids room', 'kids room'), ('playground', 'playground'), ('pet area', 'pet area'), ('pet wash', 'pet wash'), ('mini market', 'mini market'), ('near shopping mall', 'near shopping mall'), ('near supermarket', 'near supermarket'), ('near bakery', 'near bakery'), ('near pharmacy', 'near pharmacy'), ('near banks', 'near banks'), ('near park', 'near park'), ('near beach', 'near beach'), ('near schools', 'near schools'), ('near colleges', 'near colleges'), ('quiet neighborhood', 'quiet neighborhood'), ('near hospital', 'near hospital'), ('near clinics', 'near clinics'), ('near restaurants', 'near restaurants'), ('near cafes', 'near cafes'), ('near cinema', 'near cinema'), ('near cultural centers', 'near cultural centers'), ('near gym', 'near gym'), ('near gas station', 'near gas station'), ('cost benefit', 'cost benefit'), ('good for investment', 'good for investment'), ('solar panels', 'solar panels')], max_length=32), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='radarrealestatereview',
            name='good_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('paint', 'paint'), ('space', 'space'), ('condo fee', 'condo fee'), ('price', 'price'), ('finishing', 'finishing'), ('floors', 'floors'), ('ceiling', 'ceiling'), ('moldings', 'moldings'), ('natural light', 'natural light'), ('ventilation', 'ventilation'), ('windows', 'windows'), ('doors', 'doors'), ('closets', 'closets'), ('built-in cabinets', 'built-in cabinets'), ('kitchen counter', 'kitchen counter'), ('bathroom counters', 'bathroom counters'), ('air conditioning', 'air conditioning'), ('heating', 'heating'), ('fireplace', 'fireplace'), ('view', 'view'), ('balcony', 'balcony'), ('garden', 'garden'), ('landscaping', 'landscaping'), ('garage spaces', 'garage spaces'), ('guest parking', 'guest parking'), ('social elevator', 'social elevator'), ('service elevator', 'service elevator'), ('pool', 'pool'), ('party room', 'party room'), ('game room', 'game room'), ('kids room', 'kids room'), ('playground', 'playground'), ('pet area', 'pet area'), ('pet wash', 'pet wash'), ('mini market', 'mini market'), ('near shopping mall', 'near shopping mall'), ('near supermarket', 'near supermarket'), ('near bakery', 'near bakery'), ('near pharmacy', 'near pharmacy'), ('near banks', 'near banks'), ('near park', 'near park'), ('near beach', 'near beach'), ('near schools', 'near schools'), ('near colleges', 'near colleges'), ('quiet neighborhood', 'quiet neighborhood'), ('near hospital', 'near hospital'), ('near clinics', 'near clinics'), ('near restaurants', 'near restaurants'), ('near cafes', 'near cafes'), ('near cinema', 'near cinema'), ('near cultural centers', 'near cultural centers'), ('near gym', 'near gym'), ('near gas station', 'near gas station'), ('cost benefit', 'cost benefit'), ('good for investment', 'good for investment'), ('solar panels', 'solar panels')], max_length=32), null=True, size=10),
        ),
    ]
