# Generated by Django 5.2 on 2025-05-01 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creci', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=100)),
                ('address_number', models.CharField(max_length=40)),
                ('contact_number_1', models.CharField(max_length=20)),
                ('contact_number_2', models.CharField(max_length=20)),
                ('contact_whatsapp', models.CharField(max_length=20)),
                ('logo_url', models.CharField(max_length=500)),
            ],
        ),
    ]
