# Generated by Django 5.2 on 2025-05-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='profile_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
