# Generated by Django 5.2.5 on 2025-08-09 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
        migrations.CreateModel(
            name='RadarRealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_real_estate_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('preference', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('pending', 'pending')], default='pending', max_length=10)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.radar')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate')),
            ],
        ),
    ]
