# Generated by Django 5.2.5 on 2025-08-09 00:13

import django.contrib.postgres.fields
import django.db.models.deletion
import real_estate.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('price', 'price'), ('availability', 'availability')], max_length=15), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_code', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('terrain', 'terrain'), ('office', 'office'), ('store', 'store'), ('warehouse', 'warehouse'), ('rural', 'rural')], default='apartment', max_length=15)),
                ('transaction_type', models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], default='buy', max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('bedroom_quantity', models.IntegerField()),
                ('suite_quantity', models.IntegerField()),
                ('bathroom_quantity', models.IntegerField()),
                ('garage_slots_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
                ('area_total', models.FloatField()),
                ('available', models.BooleanField()),
                ('cond_price', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('thumb_url', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), default=real_estate.models.RealEstate.get_images_url_default, size=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=250)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_agency.agency')),
            ],
        ),
    ]
