# Generated by Django 5.2 on 2025-05-01 03:02

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('S1', 'price'), ('S2', 'availability')], max_length=2), size=None)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S1', 'apartment'), ('S2', 'house'), ('S3', 'terrain'), ('S4', 'office'), ('S5', 'store'), ('S6', 'warehouse'), ('S7', 'rural')], max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('bedroom_quantity', models.IntegerField()),
                ('suite_quantity', models.IntegerField()),
                ('bathroom_quantity', models.IntegerField()),
                ('garage_slots_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
                ('available', models.BooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_agency.agency')),
            ],
        ),
    ]
