# Generated by Django 5.2 on 2025-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='type',
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(choices=[('S1', 'apartment'), ('S2', 'house'), ('S3', 'terrain'), ('S4', 'office'), ('S5', 'store'), ('S6', 'warehouse'), ('S7', 'rural')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='realestate',
            name='transaction_type',
            field=models.CharField(choices=[('S1', 'buy'), ('S2', 'rent')], default='S1', max_length=2),
        ),
    ]
