# Generated by Django 5.2 on 2025-05-03 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_remove_realestate_type_realestate_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('terrain', 'terrain'), ('office', 'office'), ('store', 'store'), ('warehouse', 'warehouse'), ('rural', 'rural')], default='apartment', max_length=15),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], default='buy', max_length=15),
        ),
        migrations.AlterField(
            model_name='realestateupdate',
            name='update',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('price', 'price'), ('availability', 'availability')], max_length=15), size=None),
        ),
    ]
