# Generated by Django 5.2 on 2025-05-04 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_realestate_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='area_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='cond_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='realestate',
            name='images_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=250), default=[], size=None),
        ),
    ]
