# Generated by Django 5.2 on 2025-05-04 19:12

import django.contrib.postgres.fields
import real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_realestate_area_total_realestate_cond_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='images_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=250), default=real_estate.models.RealEstate.get_images_url_default, size=None),
        ),
    ]
