# Generated by Django 5.2 on 2025-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_alter_realestate_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='area_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='cond_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
