# Generated by Django 5.2 on 2025-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_realestate_images_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestateupdate',
            old_name='update_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='realestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
