# Generated by Django 5.2 on 2025-05-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_rename_update_at_realestateupdate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
