# Generated by Django 5.2.2 on 2025-06-22 22:59

import django.contrib.postgres.fields
import real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_realestate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='images_url',
        ),
        migrations.AddField(
            model_name='realestate',
            name='thumb_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), default=real_estate.models.RealEstate.get_images_url_default, size=50),
        ),
    ]
